### PR TITLE
SP-2470 remove refund error showing on shop

### PR DESCRIPTION
**Pull request by AbrahamOEd**

### CODE REVIEW

**Comment by tungd** [comment]
I am not sure if this is the correct fix. What will happends if the refund does indeed failed? Where would the error be shown in that case?

**Comment by AbrahamOEd** [comment]
@tungd i have tried processing refund with value 0, as well as value exceeding the order amount, both returns an error only on the dashboard instead of the store through the following dialog box
Screenshot 202
![Screenshot 2023-06-30 at 2 36 39 PM
3-06-30 at 2 40 48 PM](https://github.com/open-fabric/openfabric-woocommerce-extension/assets/125857654/911b8806-0536-439c-8d35-e0716a2e043e)

**Comment by tungd** [comment]
This is not the errors I'm talking about. From the cases you've tested, it seems like these are the valildation that WC does by itself. To be able to test server side error, I'd request you to try the following scenario:

- Create an order
- Manually refund it partially using Postman
- Try refunding the full amount with WC. This way, the amount you try to refund will still be valid as WC would not know about the partial refund via Postman, but our backend does know and would reject that refund request. If the result/error message from the backend came back then I'll accept this PR.

**Comment by AbrahamOEd** [comment]
@tungd I have tested your flow and it still produces an error on the frontend.

Steps to reproduce:

- Create order (transaction id fe7fd627-0c10-48bf-9870-edcaa085fe2f)
- Refund transaction partially (merchant id a2a5489a-ea49-44b2-be85-9773bb9d9a0a)
- Refund result:
```
{
    "id": "3f5764a1-fca4-4b88-811a-3c785f51c29a",
    "pg_refund_id": "re_3NOdASLamy29jZjm2otL8yJg",
    "data": {
        "id": "re_3NOdASLamy29jZjm2otL8yJg",
        "object": "refund",
        "amount": 1000,
        "balance_transaction": "txn_3NOdASLamy29jZjm2kWQxrrl",
        "charge": "ch_3NOdASLamy29jZjm2wMfQxFa",
        "created": 1688115577,
        "currency": "sgd",
        "metadata": {
            "partner_reference_id": "wc_order_116"
        },
        "payment_intent": null,
        "reason": null,
        "receipt_number": null,
        "source_transfer_reversal": null,
        "status": "succeeded",
        "transfer_reversal": null
    }
}
```
- Refund full amount with WC Dashboard
The following is the result of the refund, an error still pops up

Screenshot 2023-06-30 at 5 18 11 PM

**Review by tungd — APPROVED** [review]

**Pull request merged**
